bsub -q long -W 40:00 -R "rusage[mem=150000]" -oo snk.out -eo snk.err "snakemake -j 999 --latency-wait 30 --configfile $1 --printshellcmds --cluster-config cluster.json --cluster \"bsub -q {cluster.queue} -W {cluster.time} -n {cluster.nCPUs} -R {cluster.memory} -R {cluster.resources} -oo {cluster.output} -eo {cluster.error} -J {cluster.name}\""
###
# some notes on an experienced snakemaker ...
###

# (1) host span 1 is in cluster.resources ...
# (2) looks like -o and -e outputs go to .snakemake folders ...
# (3) -j is all about how many jobs could be submitted at the same time ...
# (4) why the heck __default__ was not submitted as a job and ran locally instead ?!
# (5) THIS IS THE locarule !!!!! that prevented a bunch of my jobs going to cluster ...

# (6) it seems like doing 2 independent rebalancing jobs on the same .mcool leads to crazy race condition - 
# when .mcool get modified by the other job and a corresponding touch gets out of sync ...
# solution - do rebalancing on a single .mcool in 1 process ...
